import os
import logging
from datetime import datetime

logger = logging.getLogger(__name__)

class ReportGenerator:
    def __init__(self, template_dir=None):
        if template_dir is None:
            template_dir = os.path.join(
                os.path.dirname(os.path.abspath(__file__)), "templates"
            )
        self.template_dir = template_dir
        os.makedirs(template_dir, exist_ok=True)
        os.makedirs("reports", exist_ok=True)
        self._ensure_templates()

    def _ensure_templates(self):
        sar_path = os.path.join(self.template_dir, "sar_template.html")
        if not os.path.exists(sar_path):
            with open(sar_path, "w") as f:
                f.write("""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
  h1 { color: #dc3545; border-bottom: 2px solid #dc3545; padding-bottom: 10px; }
  h2 { color: #495057; margin-top: 30px; }
  table { width: 100%; border-collapse: collapse; margin-top: 10px; }
  th { background: #343a40; color: white; padding: 8px 12px; text-align: left; }
  td { padding: 8px 12px; border-bottom: 1px solid #dee2e6; }
  tr:nth-child(even) { background: #f8f9fa; }
  .risk-high { color: #dc3545; font-weight: bold; }
  .meta { color: #6c757d; font-size: 0.9em; margin-bottom: 30px; }
  .footer { margin-top: 40px; font-size: 0.8em; color: #6c757d; border-top: 1px solid #dee2e6; padding-top: 10px; }
  .print-btn { background:#dc3545; color:white; border:none; padding:10px 20px; border-radius:5px; cursor:pointer; margin-bottom:20px; font-size:1em; }
</style>
</head>
<body>
  <button class="print-btn" onclick="window.print()">&#128438; Print / Save as PDF</button>
  <h1>Suspicious Activity Report (SAR)</h1>
  <div class="meta">
    <strong>Report Date:</strong> {{ report_date }}<br>
    <strong>Risk Threshold:</strong> {{ threshold }}<br>
    <strong>Generated By:</strong> AI Fraud Detection System
  </div>
  <h2>Customer Information</h2>
  <table>
    <tr><th>Field</th><th>Value</th></tr>
    <tr><td>Account ID</td><td>{{ customer.account_id }}</td></tr>
    <tr><td>Name</td><td>{{ customer.name }}</td></tr>
    <tr><td>Risk Score</td><td class="risk-high">{{ customer.risk_score }}</td></tr>
  </table>
  <h2>Flagged Transactions</h2>
  <table>
    <tr>
      <th>Transaction ID</th><th>Amount</th><th>Type</th>
      <th>Location</th><th>Risk Score</th><th>Status</th><th>Date</th>
    </tr>
    {% for tx in transactions %}
    <tr>
      <td>{{ tx.TransactionID }}</td>
      <td>${{ tx.TransactionAmount }}</td>
      <td>{{ tx.TransactionType }}</td>
      <td>{{ tx.Location }}</td>
      <td class="risk-high">{{ tx.RiskScore }}</td>
      <td>{{ tx.Status }}</td>
      <td>{{ tx.TransactionDate }}</td>
    </tr>
    {% endfor %}
  </table>
  <div class="footer">
    This report was automatically generated. Review by a compliance officer is required before filing.
  </div>
</body>
</html>""")

    def _render_template(self, template_name, context):
        try:
            from jinja2 import Environment, FileSystemLoader
            env = Environment(loader=FileSystemLoader(self.template_dir))
            template = env.get_template(template_name)
            return template.render(context)
        except Exception as e:
            logger.error(f"Template rendering failed: {e}")
            raise

    def generate_sar(self, transactions, customer_info, output_path):
        """Generate SAR — saves as HTML, returns the HTML content directly."""
        context = {
            "transactions": transactions,
            "customer":     customer_info,
            "report_date":  datetime.now().strftime("%Y-%m-%d %H:%M"),
            "threshold":    0.7
        }
        html = self._render_template("sar_template.html", context)
        # Save HTML file
        html_path = output_path.replace(".pdf", ".html")
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html)
        logger.info(f"Report saved: {html_path}")
        return html  # Return HTML content so route can serve it directly

    def generate_ctr(self, transactions, output_path):
        large_txns = [t for t in transactions if float(t.get('TransactionAmount', 0)) > 10000]
        context = {"transactions": large_txns, "report_date": datetime.now().strftime("%Y-%m-%d %H:%M")}
        tpl = "ctr_template.html"
        if not os.path.exists(os.path.join(self.template_dir, tpl)):
            tpl = "sar_template.html"
        html = self._render_template(tpl, context)
        html_path = output_path.replace(".pdf", ".html")
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html)
        return html

    def generate_daily_summary(self, stats, output_path):
        context = {
            "date": datetime.now().strftime("%Y-%m-%d"),
            "total_transactions": stats.get('total', 0),
            "flagged_transactions": stats.get('flagged', 0),
            "sar_filed": stats.get('sar_count', 0),
            "ctr_filed": stats.get('ctr_count', 0)
        }
        tpl = "daily_summary.html"
        if not os.path.exists(os.path.join(self.template_dir, tpl)):
            tpl = "sar_template.html"
        html = self._render_template(tpl, context)
        html_path = output_path.replace(".pdf", ".html")
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html)
        return html